# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "29b57b9ce610cc522c9845b8afa00798"
name = "demo"
application_url = "https://risk-funny-will-wx.trycloudflare.com"
embedded = true
handle = "demo-1831"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://risk-funny-will-wx.trycloudflare.com/auth/callback", "https://risk-funny-will-wx.trycloudflare.com/auth/shopify/callback", "https://risk-funny-will-wx.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
